export const errorMessage = {
  'A00001':`Server exception`,
  'A00004':`Unauthorized`,
  'A00005':`Something went wrong with the server`,
  'A00014':`Method parameters not verified`,
  'A00015':`Method parameters not verified`,
  'A00016':`User information not found`,
  'A00017':`Auction product does not exist`,
  'A00018':`The product is not under auction, auction cannot be canceled`,
  'A00019':`Auction cancelled successfully`,
  'A00020':`The auction product ID cannot be empty`,
  'A00021':`Other users have bid, please bid again`,
  'A00022':`The user's coin balance is insufficient, bid cannot be made`,
  'A00023':`The auction product does not specify a currency`,
  'A00024':`The product has been auctioned`,
  'A00025':`The user's bid cannot be less than the product's starting price`,
  'A00026':`The current user's bid is less than the product's highest bid`,
  'A00027':`The current auction product has not set a starting price`,
  'A00028':`The product ID for setting automatic bidding cannot be empty`,
  'A00029':`The set automatic bidding limit cannot be less than 0`,
  'A00030':`The user has set a bid for this product`,
  'A00031':`The user has not set an automatic bid for this product`,
  'A00032':`The set automatic bid limit cannot be less than 0`,
  'A00033':`The user is not eligible to purchase auction items`,
  'A00034':`The user has submitted an order, please do not submit it again`,
  'A00035':`Please select the items you need and add them to the shopping cart`,
  'A00036':`The auction item ID cannot be empty`,
  'A00037':`The auction item does not exist`,
  'A00038':`No permission to obtain the product specification information`,
  'A00039':`The account does not exist`,
  'A00040':`The verification code has expired`,
  'A00041':`The verification code has expired`,
  'A00042':`The account or password is incorrect`,
  'A00043':`The password has been entered incorrectly ten times, and the login has been restricted for 30 minutes`,
  'A00044':`The currency does not exist`,
  'A00045':`The user name has been registered and cannot be re-registered`,
  'A00046':`The new password cannot be empty`,
  'A00047':`The new password cannot be the same as the original password`,
  'A00048':`The brand name already exists`,
  'A00049':`The order has expired, please place an order again`,
  'A00050':`The category name already exists`,
  'A00051':`The superior of the category cannot It is yourself`,
  'A00052':`The modification failed, the parent category does not exist or is not in normal state`,
  'A00053':`Please delete the subcategory, then delete the category`,
  'A00054':`The product does not exist`,
  'A00055':`The Gmail mailbox has been registered`,
  'A00056':`The Facebook account has been registered`,
  'A00057':`At least one product specification must be enabled`,
  'A00058':`Please select the product group`,
  'A00059':`AES decryption error`,
  'A00060':`The user account credit balance is insufficient and the order cannot be submitted`,
  'A00061':`The product has been added to the promotion`,
  'A00062':`It is forbidden to modify the admin account password`,
  'A00064':`The original password is incorrect`,
  'A00065':`The product is not on the shelf, please select another product`,
  'A00066':`The label name already exists, the same label cannot be added`,
  'A00067':`The default label cannot be deleted`,
  'A00068':`You do not have permission to obtain the order information`,
  'A00069':`The order has been paid and cannot be cancelled`,
  'A00070':`The order does not exist`,
  'A00071':`The order is not completed or closed, and the order cannot be deleted`,
  'A00072':`The shopping cart contains unrecognizable items`,
  'A00073':`The item has been removed from the shelves`,
  'A00074':`The address has been deleted`,
  'A00075':`Please fill in the delivery address`,
  'A00076':`Insufficient inventory of the item`,
  'A00077':`No permission to obtain the user information`,
  'A00078':`The user already exists`,
  'A00079':`The admin user cannot be disabled`,
  'A00080':`It is forbidden to modify the admin account and password`,
  'A00081':`Please select the user to be deleted`,
  'A00082':`The current user cannot be deleted`,
  'A00083':`The system administrator cannot delete`,
  'A00084':`The menu URL cannot be empty`,
  'A00085':`You cannot be your own superior`,
  'A00086':`System menu, cannot be deleted`,
  'A00087':`The address already exists`,
  'A00088':`The default address cannot be deleted`,
  'A00089':`Bank information has been deleted`,
  'A00090':`The item has been removed from the shopping cart`,
  'A00091':`Please delete the submenu or button first`,
  'A00092':`Enter the change quantity`,
  'A00093':`The order has not been shipped, and the receipt cannot be confirmed`,
}
